export type BlogPost = {
  slug: string;
  tag: string;
  title: string;
  excerpt: string;
  readTime: string;
  date: string;
  author: string;
  content: string[]; // paragraphs / markdown-ish blocks
};

export const posts: BlogPost[] = [
  {
    slug: "seo-tactics-that-still-work-in-2026",
    tag: "SEO",
    title: "10 SEO tactics that still work in 2026",
    excerpt: "Search has changed — AI Overviews, zero-click SERPs, and stricter E-E-A-T. Here are the tactics that reliably move rankings this year.",
    readTime: "8 min read",
    date: "June 12, 2026",
    author: "BrainboxWorld Team",
    content: [
      "Search in 2026 looks very different from search in 2020. AI Overviews sit above the traditional blue links, zero-click results answer most informational queries inside the SERP, and Google's spam updates have raised the bar for what 'quality content' actually means. The good news: the fundamentals still work — they just have to be executed at a higher standard.",
      "## 1. Ship pages that answer one clear intent",
      "Every ranking page in 2026 answers one specific question for one specific searcher. Pages that try to rank for ten keywords rank for none. Before writing, define the exact query and the exact persona — then structure the whole page around that single job.",
      "## 2. Build topical authority, not keyword pages",
      "Google now rewards sites that cover a topic comprehensively. If you sell accounting software, publish everything a small-business owner needs to know about bookkeeping — not just pages targeting 'best accounting software'. Depth signals expertise; expertise wins featured snippets and AI Overview citations.",
      "## 3. Make E-E-A-T visible on the page",
      "Experience, Expertise, Authoritativeness, Trust. Show author bios with credentials, link to original research, cite primary sources, and add dates. Anonymous, undated posts get filtered out of AI Overviews.",
      "## 4. Optimise for AI Overview citations",
      "AI Overviews cite 3–8 sources per answer. To be one of them, use clear H2 questions, concise definitional first paragraphs (40–60 words), structured lists, and schema markup. Think 'quotable' — write sentences an LLM can lift verbatim.",
      "## 5. Fix Core Web Vitals — properly",
      "LCP under 2.5s, INP under 200ms, CLS under 0.1. Most sites still fail INP because of heavy third-party scripts. Audit your tag manager, defer non-critical JS, and self-host fonts.",
      "## 6. Internal linking is a growth lever, not an afterthought",
      "A well-linked pillar page can double the rankings of the cluster around it. Use descriptive anchor text, link every new post to 3–5 existing posts, and update old posts to link to new ones.",
      "## 7. Programmatic pages, done tastefully",
      "Programmatic SEO still works — but only when each page has unique value. Templates + a thin database dump gets flagged as spam. Templates + real data, real reviews, and real utility rank.",
      "## 8. Video and image search are underpriced",
      "YouTube is the second largest search engine. Google Images drives real traffic for product and how-to queries. Add original visuals, transcribe videos, and use descriptive filenames and alt text.",
      "## 9. Local SEO: Google Business Profile is 50% of the game",
      "For any business with a physical location or service area, GBP optimisation beats blog posts. Weekly posts, fresh photos, review responses, and accurate service categories move the map pack faster than backlinks.",
      "## 10. Measure what actually matters",
      "Rankings without revenue are vanity. Track assisted conversions, branded search growth, and pipeline sourced from organic. That's what proves SEO to a CFO.",
      "### The bottom line",
      "SEO in 2026 rewards teams that combine editorial quality with technical rigour. Pick the three tactics above your team can execute consistently for the next six months — and ignore the rest until you've mastered those.",
    ],
  },
  {
    slug: "what-makes-a-website-convert-in-2026",
    tag: "Web Design",
    title: "What makes a website convert in 2026",
    excerpt: "The design principles behind our highest-converting sites — clarity, speed, social proof, and one unmistakable next step.",
    readTime: "7 min read",
    date: "May 28, 2026",
    author: "BrainboxWorld Team",
    content: [
      "We've shipped over 100 websites in the last three years, and the ones that convert share a small, boring set of traits. Nothing here is a trend — trends fade. These are the fundamentals that consistently move conversion rate whether you're selling SaaS, services, or physical products.",
      "## 1. Clarity beats cleverness",
      "Above the fold, a visitor should know three things in under five seconds: what you do, who it's for, and what to do next. Clever headlines that require a second read cost you conversions. 'Marketing automation for e-commerce brands' beats 'Grow smarter, not harder' every time.",
      "## 2. One primary call to action per screen",
      "Every section should have exactly one action you want the visitor to take. Two CTAs of equal weight = decision paralysis = bounce. Make the primary action visually dominant; demote everything else to text links.",
      "## 3. Speed is a design feature",
      "A one-second delay in load time drops conversions by 7%. Design mockups need to include performance budgets: hero image under 200KB, total page weight under 1MB, LCP under 2s. If a design can't hit those numbers, it needs to change.",
      "## 4. Social proof at the point of doubt",
      "Testimonials at the bottom of the page are wasted. Put them where the visitor hesitates — next to the pricing, next to the signup form, next to the risky claim. 'Trusted by 200+ teams' means nothing; a photo, a name, a company, and a specific result means everything.",
      "## 5. Show the product, don't describe it",
      "For SaaS: real screenshots, real data, annotated. For services: before/after, case studies with numbers. For products: multiple angles, video, scale references. Stock photos of smiling people in headsets convert nothing.",
      "## 6. Mobile is the design, not a version of it",
      "70%+ of traffic is mobile. Design mobile-first — tap targets 44px minimum, forms with one field per screen, sticky CTAs, no hover-only interactions. Desktop is the adaptation, not the reverse.",
      "## 7. Reduce form friction ruthlessly",
      "Every field on a form drops conversion. Ask only what you need to make the next step happen. Name and email is usually enough. Enrich the rest from your CRM.",
      "## 8. Write for scanners",
      "People don't read websites — they scan. Short paragraphs, descriptive subheadings, bullet lists, and bolded phrases. If someone reads only the headings, can they still get the point? If not, rewrite.",
      "### The bottom line",
      "High-converting sites aren't beautiful by accident — they're built around a clear promise, one action, and enough proof to make that action feel safe. Fix those three things and conversion follows.",
    ],
  },
  {
    slug: "google-ads-vs-meta-ads-what-to-pick",
    tag: "Marketing",
    title: "Google Ads vs Meta Ads: what to pick",
    excerpt: "A practical breakdown for growing service businesses — where each channel wins, where they fail, and how to sequence them.",
    readTime: "6 min read",
    date: "May 10, 2026",
    author: "BrainboxWorld Team",
    content: [
      "The Google-vs-Meta debate is the wrong question. They serve different stages of the buying journey. The right question is: given your budget and where your buyer is in that journey, which channel should you start with?",
      "## Google Ads: capturing existing demand",
      "Google Ads shows your business to people who are actively searching for what you sell. 'Emergency plumber Lagos', 'accounting software for restaurants', 'wedding photographer Abuja' — these are people ready to buy today.",
      "Best for: local services, high-intent B2B, categories where people know what they want. Weakness: expensive for competitive keywords, poor at creating awareness for new products.",
      "## Meta Ads: creating demand",
      "Facebook and Instagram show your business to people based on their interests, behaviours, and lookalikes of your existing customers. These people weren't searching — you're interrupting their scroll to introduce a solution.",
      "Best for: visual products, impulse purchases, categories where buyers don't know your solution exists. Weakness: much longer path to conversion, needs strong creative.",
      "## How to sequence them",
      "If you have under ₦500K/month to spend and you're a service business, start with Google Ads. You'll pay more per click but the intent is higher — you get case studies and cash flow faster.",
      "Once Google is profitable and you have a proven offer, layer Meta on top to build brand awareness and retarget site visitors. The retargeting layer alone can lift conversion rate 20–30%.",
      "## The metrics that matter",
      "Ignore vanity metrics like CTR and impressions. Track cost per qualified lead, cost per sale, and 60-day LTV. A ₦5,000 lead that closes at ₦200,000 is a bargain; a ₦500 lead that never closes is expensive.",
      "### The bottom line",
      "Start with the channel closest to the money. For most service businesses, that's Google. Add Meta once you have proof and cash flow. Don't try to run both at scale until at least one is profitable.",
    ],
  },
  {
    slug: "building-a-brand-customers-remember",
    tag: "Branding",
    title: "Building a brand that customers remember",
    excerpt: "Consistency, story, and identity systems that scale from a one-person business to a hundred-person team.",
    readTime: "6 min read",
    date: "April 22, 2026",
    author: "BrainboxWorld Team",
    content: [
      "A memorable brand isn't a logo. It's the sum of every interaction a customer has with your business — the tone of your emails, the speed of your replies, the packaging your product ships in, the way your website makes them feel. Get those right and the logo is just the sticker on top.",
      "## Start with a point of view",
      "Brands that stand for something are remembered. Brands that try to appeal to everyone disappear. Before designing anything, answer: what do we believe that our competitors don't? That belief becomes the brand's spine.",
      "## Build an identity system, not a logo",
      "A logo is one asset. An identity system is a set of rules — colours, typography, spacing, photography style, illustration style, motion — that let anyone in your team create on-brand assets without asking the designer. Systems scale; logos don't.",
      "## Consistency compounds",
      "The same colours, the same voice, the same fonts everywhere for two years builds more brand equity than a rebrand every six months. Pick a system you can live with, then live with it.",
      "## Write like a human",
      "Corporate speak is invisible. 'Leverage synergies' is forgettable; 'we help you get paid faster' is not. Write the way your best salesperson talks to your best customer. Read every draft out loud — if you'd never say it, don't ship it.",
      "## Design for the small details",
      "The 404 page. The order confirmation email. The loading spinner. These are the moments customers screenshot and share. Sweat them.",
      "### The bottom line",
      "Memorable brands are built by teams that make a hundred small consistent decisions over years. Start with a point of view, codify a system, and defend both relentlessly.",
    ],
  },
  {
    slug: "the-website-audit-checklist-we-use",
    tag: "Business Growth",
    title: "The website audit checklist we use",
    excerpt: "Copy our internal audit template — the same one we run on every new client site before we propose any changes.",
    readTime: "9 min read",
    date: "April 05, 2026",
    author: "BrainboxWorld Team",
    content: [
      "Before we propose a single design change or SEO recommendation to a new client, we run this audit. It takes about two hours and covers every failure mode we've seen kill conversion. Copy it, adapt it, use it on your own site.",
      "## 1. Performance",
      "Run PageSpeed Insights on the homepage, a product/service page, and a blog post. Target LCP < 2.5s, INP < 200ms, CLS < 0.1 on mobile. If any fail, that's fix #1 before anything else.",
      "## 2. Mobile experience",
      "Load the site on a real phone, not just Chrome DevTools. Are tap targets big enough? Do forms auto-fill? Does the sticky header eat half the screen? Real devices reveal problems emulators hide.",
      "## 3. Above-the-fold clarity",
      "Show the homepage to five people who don't know your business. Ask each one: what does this company do, who is it for, and what should you do next? If any of the three isn't obvious in five seconds, rewrite the hero.",
      "## 4. Conversion path",
      "From every entry page, can a visitor reach the primary conversion (buy, book, signup) in three clicks or fewer? Map it. Anything longer costs you sales.",
      "## 5. Forms",
      "Every form field is a tax. Count them. Justify each one. Delete anything you can enrich from a CRM later.",
      "## 6. Social proof placement",
      "Are testimonials and case studies next to the moments of doubt (pricing, signup, checkout)? Or dumped in a page nobody visits? Move them.",
      "## 7. SEO basics",
      "Unique title tag under 60 chars and meta description under 160 chars on every page. One H1 per page. Descriptive alt text on every image. Sitemap.xml submitted to Search Console.",
      "## 8. Analytics and tracking",
      "Is GA4 installed? Are conversions defined and firing? Is Search Console verified? Is Meta Pixel installed with the right events? You can't improve what you can't measure.",
      "## 9. Broken links and 404s",
      "Run a crawler (Screaming Frog, Ahrefs). Fix every internal 404 and every broken outbound link. Redirect old URLs to relevant new ones.",
      "## 10. Trust signals",
      "SSL padlock, privacy policy, terms of service, business address, phone number, real photos of real people. Missing any of these on a service or e-commerce site kills conversion silently.",
      "### The bottom line",
      "Most sites don't need a redesign — they need this audit and 20 specific fixes. Do the audit before you write the brief.",
    ],
  },
  {
    slug: "design-tokens-the-secret-behind-fast-rebrands",
    tag: "Web Design",
    title: "Design tokens: the secret behind fast rebrands",
    excerpt: "How we cut redesign time in half using design tokens — and why every serious brand should be using them.",
    readTime: "5 min read",
    date: "March 18, 2026",
    author: "BrainboxWorld Team",
    content: [
      "A rebrand used to mean weeks of find-and-replace across dozens of files. With design tokens, a global brand refresh takes minutes. Here's how they work and why every team should adopt them.",
      "## What is a design token?",
      "A design token is a named variable that stores a design decision — a colour, a font size, a border radius, a shadow, a spacing unit. Instead of writing `color: #2563EB` in fifty places, you write `color: var(--color-primary)` and change the value in one place.",
      "## Why they matter",
      "Tokens turn design into a system. Change the primary colour and every button, link, and heading updates automatically. Add dark mode and every surface flips because the tokens are semantic (`--surface-primary`) not literal (`--white`).",
      "## Semantic vs literal tokens",
      "Literal tokens describe the value: `--blue-500`, `--space-16`. Semantic tokens describe the purpose: `--color-primary`, `--space-section`. Ship both — literals as the palette, semantics as the API.",
      "## Where to store them",
      "In CSS custom properties for the web, in a shared JSON file (via Style Dictionary) if you need to sync with iOS/Android/Figma. Figma Variables now sync directly with CSS custom properties, closing the loop between design and code.",
      "## The payoff",
      "The last three brand refreshes we did took under a day of engineering time each. Ten years ago the same work would have been a month. Tokens don't just save time — they make brand consistency a technical guarantee, not a design review.",
      "### The bottom line",
      "If your codebase still hardcodes colours and spacing, migrate to tokens the next time you touch the design system. Future-you will send a thank-you card.",
    ],
  },
];

export const getPost = (slug: string) => posts.find((p) => p.slug === slug);
